server:
  port: 8081
spring:
  application:
    name: springbootService
  datasource:
    url: jdbc:mysql://localhost:3306/spring-cloud?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: qeen1013
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 600
        max-wait: 10000
        max-active: 300

eureka:
  client:
    service-url:
      defaultZone: http://${eureka_host:localhost}:${eureka_port:8761}/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath*:mybatis/mapper/*/*.xml


redisprefix: demo-user-